# Parameters for already available areas
_arg:
  peril: ${runtime_params:peril, 'Precipitation excess'}
  start_indices_at: ${runtime_params:start_indices_at, '1996-01-01'}
params_summarize:
  add_abs_anom: false #true

# Parameters for creating triggers
params_indices:
  dist: 'gamma'
  start_time: ${_arg.start_indices_at}

# Viz parameters
params_series:
  title: Precipitation index construction  # optional, default: None (no suptitle)
  #figsize: [12, 7]                  # optional, default: (12, 7)
