import argparse
import yaml
import logging
from pathlib import Path
import pandas as pd
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

def load_config(config_path="config.yaml"):
    with open(config_path, "r") as f:
        return yaml.safe_load(f)

def generate_slip(config_path="config.yaml"):
    config = load_config(config_path)
    output_dir = Path(config["paths"]["output_dir"])
    
    pricing_file = output_dir / "pricing_quote.csv"
    if not pricing_file.exists():
        logging.error(f"{pricing_file} not found. Run previous steps first.")
        return
        
    pricing_df = pd.read_csv(pricing_file)
    
    # Extract combined stats
    combined_row = pricing_df[pricing_df['crop'] == 'Combined']
    
    if not combined_row.empty:
        total_premium = combined_row['commercial_premium_usd'].values[0]
        total_aal = combined_row['AAL_usd'].values[0]
    else:
        total_premium = pricing_df['commercial_premium_usd'].sum()
        total_aal = pricing_df['AAL_usd'].sum()
    
    crop_list = [c for c in pricing_df['crop'].unique() if c != 'Combined']
    regions = list(config["parameters"]["regions"].keys())
    
    slip_md = f"""# Parametric Drought Insurance - Term Slip

**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Product Name:** {config.get('pipeline', {}).get('name', 'Drought Parametric Product')}
**Regions Covered:** {', '.join(regions)}
**Crops Monitored:** {', '.join(crop_list)}

## Coverage Summary
* **Average Annual Loss (AAL):** ${total_aal:,.2f}
* **Commercial Premium:** ${total_premium:,.2f}

## Payout Structure
The policy pays out based on historical percentiles calibrated from {config["parameters"]["climatology"]["start_year"]} to {config["parameters"]["climatology"]["end_year"]}.
"""
    
    for tier, ratio in config["parameters"]["payout_structure"].items():
        slip_md += f"* **{tier}:** Pays {ratio*100:.0f}% of regional limit per hectare.\n"
        
    slip_md += "\n## Per-Crop Breakdown\n"
    slip_md += pricing_df.to_markdown(index=False)
    
    slip_md += """
    
---
*Confidential - Generated by the AI automated pricing pipeline.*
"""
    
    slip_file = output_dir / "contract_slip.md"
    with open(slip_file, "w") as f:
        f.write(slip_md)
        
    logging.info(f"Generated Contract Slip: {slip_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Step 6: Generate Presentation and Term Slip")
    parser.add_argument("--config", default="config.yaml", help="Path to config.yaml")
    args = parser.parse_args()
    
    generate_slip(args.config)
